/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockw;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Araceli
 * @author Marta
 */
public class VentanaClientes extends javax.swing.JFrame {
conectar cc= new conectar();
    Connection cn= cc.conexion();
    /**
     * Creates new form VentanaClientes
     */
    public VentanaClientes() {
        initComponents();
         mostrarstock("");
         setVisible(true);
    }
void mostrarstock(String valor){
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("Empresa");
    modelo.addColumn("CIF");
    modelo.addColumn("Email");
    modelo.addColumn("Telefono");
    modelo.addColumn("Pago");
    tabla.setModel(modelo);
    String sql="";
    if(valor.equals(""))
    {
        sql="SELECT * FROM clientes";
    }
    else{
        //sql="SELECT * FROM clientes WHERE cif='"+valor+"'";
       sql= "SELECT * FROM clientes where empresa like '%"+valor+"%'";
    }
    
    
    String [] datos = new String [5];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos [0]=rs.getString(1).toLowerCase();
                datos[1]=rs.getString(2).toLowerCase();
                datos[2]=rs.getString(3).toLowerCase();
                datos[3]=rs.getString(4).toLowerCase();
                datos[4]=rs.getString(5).toLowerCase();
                
                modelo.addRow(datos);
            }
            tabla.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(StockW.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        buscaClientes = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtempresa = new javax.swing.JTextField();
        txtpago = new javax.swing.JTextField();
        txtcif = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        añadir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StockWarehouse");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 610, 304));

        buscaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarClientes.png"))); // NOI18N
        buscaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaClientesActionPerformed(evt);
            }
        });
        getContentPane().add(buscaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 127, 112));
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 155, -1));

        jLabel1.setText("Nombre empresa:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));
        getContentPane().add(txtempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 87, -1));

        txtpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpagoActionPerformed(evt);
            }
        });
        getContentPane().add(txtpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 184, 30));
        getContentPane().add(txtcif, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 87, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 87, -1));
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 87, -1));

        añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BoGrabar.png"))); // NOI18N
        añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirActionPerformed(evt);
            }
        });
        getContentPane().add(añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 150, -1));

        jLabel6.setText("pago/dias");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, 20));

        jLabel2.setText("Empresa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel3.setText("cif");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel5.setText("telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel4.setText("email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bObORRAR.png"))); // NOI18N
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, 144, -1));

        actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BOActualizar.png"))); // NOI18N
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 720, 144, 74));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/restoVentanas.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaClientesActionPerformed
         mostrarstock(txtbuscar.getText());
    }//GEN-LAST:event_buscaClientesActionPerformed

    private void añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirActionPerformed
        try {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO clientes VALUES (?,?,?,?,?)");
            pst.setString(1, txtempresa.getText());
            pst.setString(2, txtcif.getText());
            pst.setString(3, txtemail.getText());
            pst.setString(4,txttelefono.getText());
            pst.setString(5, txtpago.getText());
            pst.executeUpdate();
            mostrarstock("");
            txtempresa.setText("");
            txtcif.setText("");
            txtemail.setText("");
            txttelefono.setText("");
            txtpago.setText("");
            
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_añadirActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        int fila = tabla.getSelectedRow();
        String borrar="";
        borrar=tabla.getValueAt(fila, 1).toString();

        try {
            PreparedStatement pst = cn.prepareStatement("DELETE FROM clientes WHERE cif='"+borrar+"'");
            pst.executeUpdate();
            mostrarstock("");

        }catch (Exception e) {
        }
    }//GEN-LAST:event_borrarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
       
         try {
            PreparedStatement pst = cn.prepareStatement("UPDATE clientes SET empresa='"+txtempresa.getText()+"',cif='"+txtcif.getText()+"',email='"+txtemail.getText()+"',telefono='"+txttelefono.getText()+"',pago='"+txtpago.getText()+"' WHERE cif='"+txtcif.getText()+"'");
            pst.executeUpdate();
            mostrarstock("");
            txtempresa.setText("");
            txtcif.setText("");
            txtpago.setText("");
            txtemail.setText("");
            txttelefono.setText("");
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void txtpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton añadir;
    private javax.swing.JButton borrar;
    private javax.swing.JButton buscaClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcif;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtempresa;
    private javax.swing.JTextField txtpago;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
